### ISSUE TITLE
PSI now returns cached versions when running subsequent requests.

### ISSUE THREAD

**Issue by charkour** [GoogleChromeLabs/psi#131]
Hello, I'm not sure where the best place is to report this issue, so please let me know!

I've noticed this past week, the PSI API (including pagespeed.web.dev) will now return cached results for subsequent requests for insights of the same URL. 

This is a hindrance when running multiple PSI requests for the same URL in hopes of using the median score due to [perf score variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) as noted on Google's Lighthouse reports. Any help would be great.

Thank you.

**Comment by jschulte** [comment]
I have recently noticed this as well. In my automated PSI testing, I now add a random URL parameter to each test to work around this issue. It's somewhat inconvenient and would be preferable if the tool would actual run a new test each time for the purpose of using the median score. Thanks!

**Comment by charkour** [comment]
That's a great idea. Thank you, @jschulte!

**Comment by jschulte** [comment]
Glad to help! I use the `uuid` module to generate the random string. https://www.npmjs.com/package/uuid

**Comment by jschulte** [comment]
As an aside, we are beginning to cache the markup of our dynamically generated pages at our CDN for better performance. The problem is that when we add the random URL parameter string to get around the cached PSI responses, it also breaks our base page markup caching and we lose the benefits of it in the test results. So, we are getting scores that are lower than they should be because even though the page is in the CDN cache for real users, the URL plus the random parameter is not.

**Comment by charkour** [comment]
Thanks, @jschulte.

Relevant discussion here: https://github.com/GoogleChrome/lighthouse/issues/14231#event-7245024641
