### ISSUE TITLE
Inconsistency of speed score when comparing to pagespeed insight website

### ISSUE THREAD

**Issue by jooj123** [GoogleChromeLabs/psi#78]
First of all - thanks for the tool 

Just wondering why when i run the cli against various websites, the speed score isnt consistent with the page speed insight website: 
https://developers.google.com/speed/pagespeed/insights/

Is this a known bug / limitation ? Or is the cli calculation meant to be different (for some reason) to the page speed site ?

**Comment by hazemhagrass** [comment]
Any updates in this ticket!

**Comment by DanielRuf** [comment]
Can you share a real example with comparable results?

**Comment by DanielRuf** [comment]
https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url=https://github.com

**Comment by DanielRuf** [comment]
Probably

We use v2 atm
https://github.com/addyosmani/psi/blob/master/index.js#L7

I guess v4 would require more changes in psi or am I wrong?

**Comment by csabapalfi** [comment]
Yes, even if I bump the version of `googleapis` and I change the version to `v4` I get this error: 
`Error: Unable to load endpoint pagespeedonline("v4"): endpoint is not a constructor`

Looks like this version is not supported by the `googleapis` module.

**Comment by DanielRuf** [comment]
So I guess we have to track this at https://github.com/google/google-api-nodejs-client as the v4 endpoint seems to be not available atm.

**Comment by DanielRuf** [comment]
Can @csabapalfi or @addyosmani or someone else create this issue or should I do it?

**Comment by csabapalfi** [comment]
I raised https://github.com/google/google-api-nodejs-client/issues/995

**Comment by King2500** [comment]
The API response field `ruleGroups.SPEED.score` is the actual "optimization score". (Because it's based on the optimization rules which where changed/refined regards their impact scores.) This tells you how much room there is for improvement. _(This score is cached for a few minutes)_

The new "speed score" is the `loadingExperience` (`overall_category` as `AVERAGE`, `FAST`, `NONE`, `SLOW`) which is loading times (FCP and DCL events) compared to real-world user data (from Chrome User Experience reports). _(This data is based on the last 30 days (if UX reports exist) and is updated weekly)_

See https://developers.google.com/speed/docs/insights/release_notes

> It adds a speed score [=loadingExperience] based on Chrome User Experience Report and refines the original PSI score [=the old SPEED.score field] as a new optimization score which mainly focuses on the relative headroom to improve.

By the way:
Obviously the `ruleGroups.USABILITY.score` field was dropped from mobile reports. :-(

**Comment by King2500** [comment]
@csabapalfi 
> Could this be because of the API versions?
> 
> See example URLs
> 
> 
> v2 - https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url=http://www.homeaway.com/d/40/austin&strategy=mobile - score 90
> 
> v4 - https://www.googleapis.com/pagespeedonline/v4/runPagespeed?url=http://www.homeaway.com/d/40/austin&strategy=mobile - score 97

I assume this difference is because the "new SPEED.score" now includes (at some parts) also the "old USABILITY.score" value.

**Comment by exterkamp** [comment]
This should be fixed in v5+ and strongly consistent with PSI website now. lmk if it isn't!
